"""Pure, stateless course-weight game model."""

from .model import (
    MODEL_VERSION,
    CourseMarket,
    CourseSelectionError,
    MarketSnapshot,
    SelectionPolicy,
    optimize_course_weights,
)
from .provider import CourseSelectionProvider
from .weight_optimizer import (
    WEIGHT_MODEL_VERSION,
    WeightCandidate,
    WeightGroupTarget,
    WeightMarketCourse,
    WeightOptimizationError,
    WeightPolicy,
    optimize_grouped_weights,
)
from .automation import CourseSelectionAutomationService
from .jwxk import (
    JWXK_CAS_SERVICE,
    JwxkBatch,
    JwxkError,
    JwxkPublicClient,
    JwxkSessionClient,
    apply_selection_market_semantics,
    normalize_course_rows,
    normalize_course_category,
    course_categories_equivalent,
    jwxk_campus_label,
    normalize_jwxk_campus_code,
    normalize_saved_plan_items,
    parse_course_detail_html,
    parse_course_eligibility,
    group_course_rows,
    parse_account_batches,
    parse_public_batches,
    resolve_network_mode,
)

__all__ = [
    "MODEL_VERSION",
    "CourseMarket",
    "CourseSelectionError",
    "CourseSelectionProvider",
    "CourseSelectionAutomationService",
    "MarketSnapshot",
    "SelectionPolicy",
    "optimize_course_weights",
    "WEIGHT_MODEL_VERSION",
    "WeightCandidate",
    "WeightGroupTarget",
    "WeightMarketCourse",
    "WeightOptimizationError",
    "WeightPolicy",
    "optimize_grouped_weights",
    "JWXK_CAS_SERVICE",
    "JwxkBatch",
    "JwxkError",
    "JwxkPublicClient",
    "JwxkSessionClient",
    "apply_selection_market_semantics",
    "normalize_course_rows",
    "normalize_course_category",
    "course_categories_equivalent",
    "jwxk_campus_label",
    "normalize_jwxk_campus_code",
    "normalize_saved_plan_items",
    "parse_course_detail_html",
    "parse_course_eligibility",
    "group_course_rows",
    "parse_account_batches",
    "parse_public_batches",
    "resolve_network_mode",
]
